Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "brown sugar")
Ingredient.create(name: "cream")
Ingredient.create(name: "Vodka")
Ingredient.create(name: "Rhum")
Ingredient.create(name: "Bacardi")
Ingredient.create(name: "coke")
Ingredient.create(name: "water")
Ingredient.create(name: "sprite")
Ingredient.create(name: "Korn")

Cocktail.create(name: 'Sex on the Beach')
Cocktail.create(name: 'Pinacolada')
Cocktail.create(name: 'Bloody Mary')
Cocktail.create(name: 'White Russian')
Cocktail.create(name: 'Margarita')
Cocktail.create(name: 'Mojito')